services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: acheiumpro
      MYSQL_USER: acheiuser
      MYSQL_PASSWORD: acheipass
    volumes:
      - db-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - '3306:3306'

volumes:
  db-data:
